name: Github Action

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    environment: production
    env:
      REGISTRY: ghcr.io
      IMAGE_NAME: ${{ github.repository }}
      COMMIT_ID: $(git rev-parse --short ${{ github.sha }})
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - shell: bash
        run: echo ${{github.sha}} > tag.txt
      - run: cat tag.txt
      - run: echo {{ env.COMMIT_ID }}