name: Github Action

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: commit
        run: echo ${{github.sha}}

      - shell: bash
        run: |
          echo ${{github.sha}} > tag.txt
      - run: cat tag.txt